### PR TITLE
Do caretRect: in main thread

### LINKED ISSUE #31: Issue on ensureCaretDisplaysCorrectly()
Using v1.1.0
simulator iphone 6s ios 9.3

Log show
requesting caretRectForPosition: while the NSTextStorage has oustanding changes {2, 1}
requesting caretRectForPosition: while the NSTextStorage has oustanding changes {3, 1}
on enter tap (new line)

possible fix:
```
        dispatch_async(dispatch_get_main_queue()) { 
            self.ensureCaretDisplaysCorrectly()
        }
```

### PR DESCRIPTION
**Pull request by FromAtom**
Hello! 

This Pull Request is to fix #31.
`caretRect(for: )` is need to exec on main thread. so, I moved this function call in `DispatchQueue.main.async`.

### CODE REVIEW

**Comment by AlexLittlejohn** [comment]
Thanks for this fix

**Comment by FromAtom** [comment]
@AlexLittlejohn Why did you delete `DispatchQueue.main.async` at https://github.com/AlexLittlejohn/ALTextInputBar/commit/2a2276dbe76c062b42bda6a25b43efe90e8c78e6 ?

**Comment by AlexLittlejohn** [comment]
Whoops, that was a mistake

**Comment by AlexLittlejohn** [comment]
Pushed v1.1.5 with this fix, apologies

**Pull request closed without merging**
